In [67]:
import numpy
import matplotlib.pyplot as plt
import gym
from dqn import DQN
import torch as tr
import gym


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [74]:
# setup
env = gym.make('CartPole-v1')
qnet = DQN()
loss = tr.nn.SmoothL1Loss()
optimizer = tr.optim.RMSprop(qnet.parameters())

In [153]:
# loop over episode
env.reset()

max_ep_len = 20
done = False
tstep = 0
env_out = env.step(0)
while not done and tstep<max_ep_len:
    obs_t,r_t,done,extra = env_out
    (c_pos,c_vel,p_ang,p_vel) = obs_t
    q_t = qnet(obs_t)
    a_t = tr.argmax(q_t)
    print(q_t,done)
    tstep += 1 
    env_out = env.step(a_t.detach().numpy())
    
    
env.close()

tensor([[ 0.0865, -0.1742]], grad_fn=<AddmmBackward>) False
tensor([[ 0.0764, -0.1872]], grad_fn=<AddmmBackward>) False
tensor([[ 0.0664, -0.2002]], grad_fn=<AddmmBackward>) False
tensor([[ 0.0662, -0.2005]], grad_fn=<AddmmBackward>) False
tensor([[ 0.0664, -0.2000]], grad_fn=<AddmmBackward>) False
tensor([[ 0.0669, -0.1989]], grad_fn=<AddmmBackward>) False
tensor([[ 0.0663, -0.1952]], grad_fn=<AddmmBackward>) False
tensor([[ 0.0659, -0.1912]], grad_fn=<AddmmBackward>) False
tensor([[ 0.0656, -0.1868]], grad_fn=<AddmmBackward>) False
tensor([[ 0.0656, -0.1821]], grad_fn=<AddmmBackward>) True


# resources
- [torch DQN tutorial](https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html)
- [blog post](https://towardsdatascience.com/deep-q-learning-for-the-cartpole-44d761085c2f)